
name: Pull Request Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Step 1 - Get code
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Step 3 - Start container
        id: docker-compose
        run: docker-compose up -d

      - name: Step 4 - Generate coverage
        id: coverage-generate
        run: mvn test

      - name: Step 5 - Coverage check
        id: coverage-check
        run: mvn verify

      - name: Step 6 - Coverage upload
        id: coverage-upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov

      - name: Step 7 - Slack
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflow'
        if: always()